/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package j2se.xe.github.jdbc;

import j2se.xe.github.dao.*;
import j2se.xe.github.factory.*;
import java.util.Date;
import j2se.xe.github.dto.*;
import j2se.xe.github.exceptions.*;
import java.sql.Connection;
import java.util.Collection;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Time;
import java.util.List;
import java.util.Iterator;
import java.util.ArrayList;

public class TestUsersDaoImpl extends AbstractDAO implements TestUsersDao
{
	/** 
	 * The factory class for this DAO has two versions of the create() method - one that
takes no arguments and one that takes a Connection argument. If the Connection version
is chosen then the connection will be stored in this attribute and will be used by all
calls to this DAO, otherwise a new Connection will be allocated for each operation.
	 */
	protected java.sql.Connection userConn;

	/** 
	 * All finder methods in this class use this SELECT constant to build their queries
	 */
	protected final String SQL_SELECT = "SELECT USER_ID, USER_NAME, USER_ADDRESS, USER_MOBILE, USER_HIRE_DATE, USER_DESCRIPTION FROM " + getTableName() + "";

	/** 
	 * Finder methods will pass this value to the JDBC setMaxRows method
	 */
	protected int maxRows;

	/** 
	 * SQL INSERT statement for this table
	 */
	protected final String SQL_INSERT = "INSERT INTO " + getTableName() + " ( USER_ID, USER_NAME, USER_ADDRESS, USER_MOBILE, USER_HIRE_DATE, USER_DESCRIPTION ) VALUES ( ?, ?, ?, ?, ?, ? )";

	/** 
	 * SQL UPDATE statement for this table
	 */
	protected final String SQL_UPDATE = "UPDATE " + getTableName() + " SET USER_ID = ?, USER_NAME = ?, USER_ADDRESS = ?, USER_MOBILE = ?, USER_HIRE_DATE = ?, USER_DESCRIPTION = ? WHERE USER_ID = ?";

	/** 
	 * SQL DELETE statement for this table
	 */
	protected final String SQL_DELETE = "DELETE FROM " + getTableName() + " WHERE USER_ID = ?";

	/** 
	 * Index of column USER_ID
	 */
	protected static final int COLUMN_USER_ID = 1;

	/** 
	 * Index of column USER_NAME
	 */
	protected static final int COLUMN_USER_NAME = 2;

	/** 
	 * Index of column USER_ADDRESS
	 */
	protected static final int COLUMN_USER_ADDRESS = 3;

	/** 
	 * Index of column USER_MOBILE
	 */
	protected static final int COLUMN_USER_MOBILE = 4;

	/** 
	 * Index of column USER_HIRE_DATE
	 */
	protected static final int COLUMN_USER_HIRE_DATE = 5;

	/** 
	 * Index of column USER_DESCRIPTION
	 */
	protected static final int COLUMN_USER_DESCRIPTION = 6;

	/** 
	 * Number of columns
	 */
	protected static final int NUMBER_OF_COLUMNS = 6;

	/** 
	 * Index of primary-key column USER_ID
	 */
	protected static final int PK_COLUMN_USER_ID = 1;

	/** 
	 * Inserts a new row in the TEST_USERS table.
	 */
	public TestUsersPk insert(TestUsers dto) throws TestUsersDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			stmt = conn.prepareStatement( SQL_INSERT );
			int index = 1;
			stmt.setInt( index++, dto.getUserId() );
			stmt.setString( index++, dto.getUserName() );
			stmt.setString( index++, dto.getUserAddress() );
			stmt.setString( index++, dto.getUserMobile() );
			stmt.setTimestamp(index++, dto.getUserHireDate()==null ? null : new java.sql.Timestamp( dto.getUserHireDate().getTime() ) );
			stmt.setString( index++, dto.getUserDescription() );
			System.out.println( "Executing " + SQL_INSERT + " with DTO: " + dto );
			int rows = stmt.executeUpdate();
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
			reset(dto);
			return dto.createPk();
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new TestUsersDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Updates a single row in the TEST_USERS table.
	 */
	public void update(TestUsersPk pk, TestUsers dto) throws TestUsersDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			System.out.println( "Executing " + SQL_UPDATE + " with DTO: " + dto );
			stmt = conn.prepareStatement( SQL_UPDATE );
			int index=1;
			stmt.setInt( index++, dto.getUserId() );
			stmt.setString( index++, dto.getUserName() );
			stmt.setString( index++, dto.getUserAddress() );
			stmt.setString( index++, dto.getUserMobile() );
			stmt.setTimestamp(index++, dto.getUserHireDate()==null ? null : new java.sql.Timestamp( dto.getUserHireDate().getTime() ) );
			stmt.setString( index++, dto.getUserDescription() );
			stmt.setInt( 7, pk.getUserId() );
			int rows = stmt.executeUpdate();
			reset(dto);
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new TestUsersDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Deletes a single row in the TEST_USERS table.
	 */
	public void delete(TestUsersPk pk) throws TestUsersDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			System.out.println( "Executing " + SQL_DELETE + " with PK: " + pk );
			stmt = conn.prepareStatement( SQL_DELETE );
			stmt.setInt( 1, pk.getUserId() );
			int rows = stmt.executeUpdate();
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new TestUsersDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Returns the rows from the TEST_USERS table that matches the specified primary-key value.
	 */
	public TestUsers findByPrimaryKey(TestUsersPk pk) throws TestUsersDaoException
	{
		return findByPrimaryKey( pk.getUserId() );
	}

	/** 
	 * Returns all rows from the TEST_USERS table that match the criteria 'USER_ID = :userId'.
	 */
	public TestUsers findByPrimaryKey(int userId) throws TestUsersDaoException
	{
		TestUsers ret[] = findByDynamicSelect( SQL_SELECT + " WHERE USER_ID = ?", new Object[] {  new Integer(userId) } );
		return ret.length==0 ? null : ret[0];
	}

	/** 
	 * Returns all rows from the TEST_USERS table that match the criteria ''.
	 */
	public TestUsers[] findAll() throws TestUsersDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " ORDER BY USER_ID", null );
	}

	/** 
	 * Returns all rows from the TEST_USERS table that match the criteria 'USER_ID = :userId'.
	 */
	public TestUsers[] findWhereUserIdEquals(int userId) throws TestUsersDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE USER_ID = ? ORDER BY USER_ID", new Object[] {  new Integer(userId) } );
	}

	/** 
	 * Returns all rows from the TEST_USERS table that match the criteria 'USER_NAME = :userName'.
	 */
	public TestUsers[] findWhereUserNameEquals(String userName) throws TestUsersDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE USER_NAME = ? ORDER BY USER_NAME", new Object[] { userName } );
	}

	/** 
	 * Returns all rows from the TEST_USERS table that match the criteria 'USER_ADDRESS = :userAddress'.
	 */
	public TestUsers[] findWhereUserAddressEquals(String userAddress) throws TestUsersDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE USER_ADDRESS = ? ORDER BY USER_ADDRESS", new Object[] { userAddress } );
	}

	/** 
	 * Returns all rows from the TEST_USERS table that match the criteria 'USER_MOBILE = :userMobile'.
	 */
	public TestUsers[] findWhereUserMobileEquals(String userMobile) throws TestUsersDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE USER_MOBILE = ? ORDER BY USER_MOBILE", new Object[] { userMobile } );
	}

	/** 
	 * Returns all rows from the TEST_USERS table that match the criteria 'USER_HIRE_DATE = :userHireDate'.
	 */
	public TestUsers[] findWhereUserHireDateEquals(Date userHireDate) throws TestUsersDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE USER_HIRE_DATE = ? ORDER BY USER_HIRE_DATE", new Object[] { userHireDate==null ? null : new java.sql.Timestamp( userHireDate.getTime() ) } );
	}

	/** 
	 * Returns all rows from the TEST_USERS table that match the criteria 'USER_DESCRIPTION = :userDescription'.
	 */
	public TestUsers[] findWhereUserDescriptionEquals(String userDescription) throws TestUsersDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE USER_DESCRIPTION = ? ORDER BY USER_DESCRIPTION", new Object[] { userDescription } );
	}

	/**
	 * Method 'TestUsersDaoImpl'
	 * 
	 */
	public TestUsersDaoImpl()
	{
	}

	/**
	 * Method 'TestUsersDaoImpl'
	 * 
	 * @param userConn
	 */
	public TestUsersDaoImpl(final java.sql.Connection userConn)
	{
		this.userConn = userConn;
	}

	/** 
	 * Sets the value of maxRows
	 */
	public void setMaxRows(int maxRows)
	{
		this.maxRows = maxRows;
	}

	/** 
	 * Gets the value of maxRows
	 */
	public int getMaxRows()
	{
		return maxRows;
	}

	/**
	 * Method 'getTableName'
	 * 
	 * @return String
	 */
	public String getTableName()
	{
		return "GITHUB.TEST_USERS";
	}

	/** 
	 * Fetches a single row from the result set
	 */
	protected TestUsers fetchSingleResult(ResultSet rs) throws SQLException
	{
		if (rs.next()) {
			TestUsers dto = new TestUsers();
			populateDto( dto, rs);
			return dto;
		} else {
			return null;
		}
		
	}

	/** 
	 * Fetches multiple rows from the result set
	 */
	protected TestUsers[] fetchMultiResults(ResultSet rs) throws SQLException
	{
		Collection resultList = new ArrayList();
		while (rs.next()) {
			TestUsers dto = new TestUsers();
			populateDto( dto, rs);
			resultList.add( dto );
		}
		
		TestUsers ret[] = new TestUsers[ resultList.size() ];
		resultList.toArray( ret );
		return ret;
	}

	/** 
	 * Populates a DTO with data from a ResultSet
	 */
	protected void populateDto(TestUsers dto, ResultSet rs) throws SQLException
	{
		dto.setUserId( rs.getInt( COLUMN_USER_ID ) );
		dto.setUserName( rs.getString( COLUMN_USER_NAME ) );
		dto.setUserAddress( rs.getString( COLUMN_USER_ADDRESS ) );
		dto.setUserMobile( rs.getString( COLUMN_USER_MOBILE ) );
		dto.setUserHireDate( rs.getTimestamp(COLUMN_USER_HIRE_DATE ) );
		dto.setUserDescription( rs.getString( COLUMN_USER_DESCRIPTION ) );
	}

	/** 
	 * Resets the modified attributes in the DTO
	 */
	protected void reset(TestUsers dto)
	{
	}

	/** 
	 * Returns all rows from the TEST_USERS table that match the specified arbitrary SQL statement
	 */
	public TestUsers[] findByDynamicSelect(String sql, Object[] sqlParams) throws TestUsersDaoException
	{
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			// construct the SQL statement
			final String SQL = sql;
		
		
			System.out.println( "Executing " + SQL );
			// prepare statement
			stmt = conn.prepareStatement( SQL );
			stmt.setMaxRows( maxRows );
		
			// bind parameters
			for (int i=0; sqlParams!=null && i<sqlParams.length; i++ ) {
				stmt.setObject( i+1, sqlParams[i] );
			}
		
		
			rs = stmt.executeQuery();
		
			// fetch the results
			return fetchMultiResults(rs);
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new TestUsersDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(rs);
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Returns all rows from the TEST_USERS table that match the specified arbitrary SQL statement
	 */
	public TestUsers[] findByDynamicWhere(String sql, Object[] sqlParams) throws TestUsersDaoException
	{
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			// construct the SQL statement
			final String SQL = SQL_SELECT + " WHERE " + sql;
		
		
			System.out.println( "Executing " + SQL );
			// prepare statement
			stmt = conn.prepareStatement( SQL );
			stmt.setMaxRows( maxRows );
		
			// bind parameters
			for (int i=0; sqlParams!=null && i<sqlParams.length; i++ ) {
				stmt.setObject( i+1, sqlParams[i] );
			}
		
		
			rs = stmt.executeQuery();
		
			// fetch the results
			return fetchMultiResults(rs);
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new TestUsersDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(rs);
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

}
