/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */


package j2se.xe.github.exceptions;

public class TestEmpsDaoException extends DaoException
{
	/**
	 * Method 'TestEmpsDaoException'
	 * 
	 * @param message
	 */
	public TestEmpsDaoException(String message)
	{
		super(message);
	}

	/**
	 * Method 'TestEmpsDaoException'
	 * 
	 * @param message
	 * @param cause
	 */
	public TestEmpsDaoException(String message, Throwable cause)
	{
		super(message, cause);
	}

}
