/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package j2se.xe.github.factory;

import java.sql.Connection;
import j2se.xe.github.dao.*;
import j2se.xe.github.jdbc.*;

public class TestUsersDaoFactory
{
	/**
	 * Method 'create'
	 * 
	 * @return TestUsersDao
	 */
	public static TestUsersDao create()
	{
		return new TestUsersDaoImpl();
	}

	/**
	 * Method 'create'
	 * 
	 * @param conn
	 * @return TestUsersDao
	 */
	public static TestUsersDao create(Connection conn)
	{
		return new TestUsersDaoImpl( conn );
	}

}
