/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package j2se.xe.github.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/** 
 * This class represents the primary key of the TEST_EMPS table.
 */
public class TestEmpsPk implements Serializable
{
	protected int empId;

	/** 
	 * This attribute represents whether the primitive attribute empId is null.
	 */
	protected boolean empIdNull;

	/** 
	 * Sets the value of empId
	 */
	public void setEmpId(int empId)
	{
		this.empId = empId;
	}

	/** 
	 * Gets the value of empId
	 */
	public int getEmpId()
	{
		return empId;
	}

	/**
	 * Method 'TestEmpsPk'
	 * 
	 */
	public TestEmpsPk()
	{
	}

	/**
	 * Method 'TestEmpsPk'
	 * 
	 * @param empId
	 */
	public TestEmpsPk(final int empId)
	{
		this.empId = empId;
	}

	/** 
	 * Sets the value of empIdNull
	 */
	public void setEmpIdNull(boolean empIdNull)
	{
		this.empIdNull = empIdNull;
	}

	/** 
	 * Gets the value of empIdNull
	 */
	public boolean isEmpIdNull()
	{
		return empIdNull;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof TestEmpsPk)) {
			return false;
		}
		
		final TestEmpsPk _cast = (TestEmpsPk) _other;
		if (empId != _cast.empId) {
			return false;
		}
		
		if (empIdNull != _cast.empIdNull) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + empId;
		_hashCode = 29 * _hashCode + (empIdNull ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "j2se.xe.github.dto.TestEmpsPk: " );
		ret.append( "empId=" + empId );
		return ret.toString();
	}

}
