/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package j2se.xe.github.dto;

import j2se.xe.github.dao.*;
import j2se.xe.github.factory.*;
import j2se.xe.github.exceptions.*;
import java.io.Serializable;
import java.util.*;
import java.util.Date;

public class TestEmps implements Serializable
{
	/** 
	 * This attribute maps to the column EMP_ID in the TEST_EMPS table.
	 */
	protected int empId;

	/** 
	 * This attribute maps to the column EMP_NAME in the TEST_EMPS table.
	 */
	protected String empName;

	/** 
	 * This attribute maps to the column EMP_SALARY in the TEST_EMPS table.
	 */
	protected int empSalary;

	/** 
	 * This attribute represents whether the primitive attribute empSalary is null.
	 */
	protected boolean empSalaryNull = true;

	/** 
	 * This attribute maps to the column EMP_HIRE_DATE in the TEST_EMPS table.
	 */
	protected Date empHireDate;

	/** 
	 * This attribute maps to the column EMP_ADDRESS in the TEST_EMPS table.
	 */
	protected String empAddress;

	/** 
	 * This attribute maps to the column EMP_NID in the TEST_EMPS table.
	 */
	protected String empNid;

	/**
	 * Method 'TestEmps'
	 * 
	 */
	public TestEmps()
	{
	}

	/**
	 * Method 'getEmpId'
	 * 
	 * @return int
	 */
	public int getEmpId()
	{
		return empId;
	}

	/**
	 * Method 'setEmpId'
	 * 
	 * @param empId
	 */
	public void setEmpId(int empId)
	{
		this.empId = empId;
	}

	/**
	 * Method 'getEmpName'
	 * 
	 * @return String
	 */
	public String getEmpName()
	{
		return empName;
	}

	/**
	 * Method 'setEmpName'
	 * 
	 * @param empName
	 */
	public void setEmpName(String empName)
	{
		this.empName = empName;
	}

	/**
	 * Method 'getEmpSalary'
	 * 
	 * @return int
	 */
	public int getEmpSalary()
	{
		return empSalary;
	}

	/**
	 * Method 'setEmpSalary'
	 * 
	 * @param empSalary
	 */
	public void setEmpSalary(int empSalary)
	{
		this.empSalary = empSalary;
		this.empSalaryNull = false;
	}

	/**
	 * Method 'setEmpSalaryNull'
	 * 
	 * @param value
	 */
	public void setEmpSalaryNull(boolean value)
	{
		this.empSalaryNull = value;
	}

	/**
	 * Method 'isEmpSalaryNull'
	 * 
	 * @return boolean
	 */
	public boolean isEmpSalaryNull()
	{
		return empSalaryNull;
	}

	/**
	 * Method 'getEmpHireDate'
	 * 
	 * @return Date
	 */
	public Date getEmpHireDate()
	{
		return empHireDate;
	}

	/**
	 * Method 'setEmpHireDate'
	 * 
	 * @param empHireDate
	 */
	public void setEmpHireDate(Date empHireDate)
	{
		this.empHireDate = empHireDate;
	}

	/**
	 * Method 'getEmpAddress'
	 * 
	 * @return String
	 */
	public String getEmpAddress()
	{
		return empAddress;
	}

	/**
	 * Method 'setEmpAddress'
	 * 
	 * @param empAddress
	 */
	public void setEmpAddress(String empAddress)
	{
		this.empAddress = empAddress;
	}

	/**
	 * Method 'getEmpNid'
	 * 
	 * @return String
	 */
	public String getEmpNid()
	{
		return empNid;
	}

	/**
	 * Method 'setEmpNid'
	 * 
	 * @param empNid
	 */
	public void setEmpNid(String empNid)
	{
		this.empNid = empNid;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof TestEmps)) {
			return false;
		}
		
		final TestEmps _cast = (TestEmps) _other;
		if (empId != _cast.empId) {
			return false;
		}
		
		if (empName == null ? _cast.empName != empName : !empName.equals( _cast.empName )) {
			return false;
		}
		
		if (empSalary != _cast.empSalary) {
			return false;
		}
		
		if (empSalaryNull != _cast.empSalaryNull) {
			return false;
		}
		
		if (empHireDate == null ? _cast.empHireDate != empHireDate : !empHireDate.equals( _cast.empHireDate )) {
			return false;
		}
		
		if (empAddress == null ? _cast.empAddress != empAddress : !empAddress.equals( _cast.empAddress )) {
			return false;
		}
		
		if (empNid == null ? _cast.empNid != empNid : !empNid.equals( _cast.empNid )) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + empId;
		if (empName != null) {
			_hashCode = 29 * _hashCode + empName.hashCode();
		}
		
		_hashCode = 29 * _hashCode + empSalary;
		_hashCode = 29 * _hashCode + (empSalaryNull ? 1 : 0);
		if (empHireDate != null) {
			_hashCode = 29 * _hashCode + empHireDate.hashCode();
		}
		
		if (empAddress != null) {
			_hashCode = 29 * _hashCode + empAddress.hashCode();
		}
		
		if (empNid != null) {
			_hashCode = 29 * _hashCode + empNid.hashCode();
		}
		
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return TestEmpsPk
	 */
	public TestEmpsPk createPk()
	{
		return new TestEmpsPk(empId);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "j2se.xe.github.dto.TestEmps: " );
		ret.append( "empId=" + empId );
		ret.append( ", empName=" + empName );
		ret.append( ", empSalary=" + empSalary );
		ret.append( ", empHireDate=" + empHireDate );
		ret.append( ", empAddress=" + empAddress );
		ret.append( ", empNid=" + empNid );
		return ret.toString();
	}

}
